chord_progs = {
        "I V vi IV": [("Enrique Iglesias", "Bailando"),
                      ("Bob Marley", "No woman no cry"),
                      ("The Beatles", "Let it be")],
        "I ii vi IV": [("Beyonce", "Halo"),
                       ("Rihanna", "Stay"),
                       ("Katy Perry", "Firework")],
        "I iii vi IV": [("Jessie J", "Pricetag"),
                        ("Blow me", "Pink"),
                        ("Count on me", "Bruno Mars")],
        "I vi ii V": [("Bruce Springsteen", "Hungry Heart")],
        "I vi IV V": [("Ben E. King", "Stand By Me"),
                      ("Sean Kingston", "Beautiful girls"),
                      ("Justin Bieber", "Baby")],
        "I IV V IV": [("Ritchie Valens", "La bamba")],
        "I V ii IV": [("Hot n cold", "Katy Perry"),
                      ("Lady Gaga", "Eh Eh"),
                      ("On my way", "Charlie Brown"),
                      ("Foster the people", "Pumped up kicks")],
        "ii IV I V": [("Paradise", "Coldplay")],
        "IV I V vi": [("Rihanna", "Umbrella"),
                      ("Grenday", "Boulevard of broken dreams"),
                      ("Passenger", "Let her go")],
        "I V vi iii IV I IV V": [("Oasis", "Don't look back in anger"),
                                 ("Maroon 5", "Memories"),
                                 ("David Bowie", "Changes")],
        "V IV I": [("Guns 'n' roses", "Sweet child o mine"),
                   ("The eagles", "Sweet home, Alabama")],
        "vi IV I V": [("Red Hot Chilly Peppers", "Snow")]
        }
